/**
 * Inline the thmanyah faces into a CSS file as data URIs.
 *
 * The licence permits embedding in a website "only as part of a compiled,
 * packaged, or obfuscated product", and forbids making the Font Software
 * available in any way that lets third parties download it as font files.
 * A normal Vite build emits each .woff2 as a standalone asset under /assets/,
 * which is exactly the prohibited shape.
 *
 * Embedding them in the stylesheet means the build ships no font files at all.
 *
 * Only the faces the design actually uses are included — Sans and Serif
 * Display at Regular and Medium. The other eleven were being downloaded by
 * every visitor for nothing.
 *
 * Run: pnpm fonts:embed   (regenerate after changing which weights are used)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const FONT_DIR = join(import.meta.dirname, "..", "client", "src", "design-system", "assets", "fonts");
const OUT = join(import.meta.dirname, "..", "client", "src", "design-system", "tokens", "fonts.css");

type Face = { family: string; file: string; weight: number };

const FACES: Face[] = [
  { family: "Thmanyah Sans", file: "thmanyahsans-Regular.woff2", weight: 400 },
  { family: "Thmanyah Sans", file: "thmanyahsans-Medium.woff2", weight: 500 },
  { family: "Thmanyah Serif Display", file: "thmanyahserifdisplay-Regular.woff2", weight: 400 },
  { family: "Thmanyah Serif Display", file: "thmanyahserifdisplay-Medium.woff2", weight: 500 },
];

const header = `/*
 * GENERATED by scripts/embed-fonts.ts — do not edit by hand.
 *
 * The thmanyah faces are inlined as data URIs so the build emits no separate
 * font files. See client/src/design-system/FONT-LICENSE.md for why.
 */
`;

const rules = FACES.map(({ family, file, weight }) => {
  const base64 = readFileSync(join(FONT_DIR, file)).toString("base64");
  return `@font-face{font-family:"${family}";src:url("data:font/woff2;base64,${base64}") format("woff2");font-weight:${weight};font-style:normal;font-display:swap}`;
});

writeFileSync(OUT, header + rules.join("\n") + "\n");

const bytes = rules.reduce((total, rule) => total + rule.length, 0);
console.log(`Embedded ${FACES.length} faces into tokens/fonts.css (${(bytes / 1024).toFixed(0)} KB of CSS).`);
for (const face of FACES) console.log(`  ${face.family} ${face.weight} — ${face.file}`);
